### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-css-sass-intro-8dVLYn#1]
@egillespie Can you take a look at this? It's [hosted here](https://kisyular.github.io/MI-449-SS17-740-css-sass-intro-8dVLYn/) and meets the following criteria:

- [x] All components in [this HTML](https://gist.github.com/egillespie/15433761e640077f93660b4555a3d88b) are styled using Sass
- [x] Use four colors from a [random color palette](https://coolors.co/) (just copy the hex values into your Sass file) and link to your palette in the HTML
- [x] Font sizes are all determined by one base font size variable, even in `input` and `textarea` elements
- [x] All text uses the same font family, even in `input` and `textarea` elements
- [x] Elements shaped like a box (`img`, `input[type="text"]`, `textarea`) have the same `border-radius`
- [x] At least one built-in Sass function is used to style a component
- [x] Variables are defined in their own Sass file
- [x] Sass files are saved in a `source` directory and CSS files are saved in a `compiled` directory
- [x] A source map for your component library is included in the project

**Comment by egillespie** [comment]
Hi @kisyular, you're off to a good start. 🦑 

I see you've created variables for many of the colors, but you're not using several of them. Do you mind making sure at least four colors from the generate palette are visible on the page?

Can you also lint your `.scss` files? Right now everything is packed tightly together and not as easy to read as it could be. Here's what I see in Atom:

![image](https://cloud.githubusercontent.com/assets/5572255/24365815/2eefb5aa-12e5-11e7-8aa6-a90b023f9c86.png)

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by kisyular** [comment]
@egillespie, I made the changes. I formatted my SCSS document more cleaner and I used all the variable names in my _variable.scss

**Comment by egillespie** [comment]
Thanks for using more colors. I'm still not seeing all of them on the page... I think it's because you created a style class for `.button` instead of applying those styles to `input[type="button"]`.

### More on linting

I see you formatted your code, but I would like to see your Sass files pass linting. Please revisit [this less](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/css-stealing-styles/1) and follow the instructions to install the CSS linter. You may also want to revisit our [introduction to linting](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/html-boilerplate-linting-and-code-style/2) to understand why it is helpful to write code that conforms to standards that can be automatically checked by linters versus just tidying up code by hand.

### Styling consistently

One of the beauties of Sass is that you can nest and inherit styles. I see you've done this a little bit with tables (and they look good because of it 👍). All of the form elements could use a similar treatment.

In a component library, you want to portray a consistent visual identity for a website. Right now, your buttons, text inputs, text areas, checkboxes, and radio buttons all have different styles.

Try using Sass nesting to apply a basic set of styles to all of those elements and then apply additional styles to more specific styles using nesting. The structure will look something like this:

```scss
input,
textarea {
  // basic styles here

  &[type="button"] {
    // button-specific styles here

    &.danger {
      // danger button styles here
    }
  }
}
```

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🏓

**Comment by kisyular** [comment]
Hi @egillespie,

I fixed the linting issue

**Comment by egillespie** [comment]
Awesome, I'm glad we were able to figure that out! Your nested styles look great too. :shipit:
